### ISSUE TITLE
NPM: Package Not Found

### ISSUE THREAD

**Issue by gyenabubakar** [tobiasdiez/unplugin-storybook-vue#17]
I tried running `npm i -D storybook-vue-addon` in a project but I got this error:

<img width="975" alt="Screenshot 2022-11-25 at 7 45 18 PM" src="https://user-images.githubusercontent.com/26672526/204049107-212e7d72-2f2f-4f19-ba57-8a5a045b390c.png">

**Comment by tobiasdiez** [comment]
Yes, it's not yet published to npm as I have to wait for https://github.com/storybookjs/builder-vite/pull/505 to be merged before.

But thanks for your interest, I keep you updated once it's published.

**Comment by gyenabubakar** [comment]
I see the issue is still open eh 😅

**Comment by tobiasdiez** [comment]
A first preview is now released at https://www.npmjs.com/package/storybook-vue-addon. Please feel free to try it out (and open issues for all problems or missing features you encounter).
